

trigger:
- main

pool: Default
  

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Ejemplo1'
    organization: 'bpbreinerpacheco0621'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'bpbreinerpacheco0621_Ejemplo'
    cliProjectName: 'Ejemplo'
    cliSources: '.'
- task: SonarCloudAnalyze@1