# Xcode

# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool: Default
  

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Ejemplo1'
    organization: 'bpbreinerpacheco0621'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'bpbreinerpacheco0621_Ejemplo'
    cliProjectName: 'Ejemplo'
    cliSources: '.'
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
- task: SonarCloudAnalyze@1